### ISSUE TITLE
D4rkPlayerOptimizer crashes VRCConstraint

### ISSUE THREAD

**Issue by QueenOfFrance** [d4rkc0d3r/d4rkAvatarOptimizer#123]
After several hours spent with the creator and developer of VRCFury trying to understand where the bug was coming from or if the constraints were not working, we only concluded that D4rkPlayerOptimizer is crashing the VRCContraint
As a solution to crossing the fence! disable “Remove unused components”

**Comment by SenkyDragon** [comment]
FindAllPhysBoneDependencies considers unity constraints but not vrc constraints.

**Comment by d4rkc0d3r** [comment]
`FindAllPhysBoneDependencies` ofc needs fixing but I find it unlikely this is causing a crash. All it should do is accidentally delete physbones if the only effect they have is moving transforms that are exclusively used by VRCConstraints and nothing else.

**Comment by SenkyDragon** [comment]
They weren't actually receiving a crash. Your description matches the issue that was occuring. It's relatively common for creators to use a set of false bones for a renderer, and then constrain those bones between different physbones so they can animate between the two smoothly (since you can't animate physbone properties smoothly)

**Comment by d4rkc0d3r** [comment]
If thats the case, putting the affected phys bones into the exclusion list would also work until the patch goes live.

**Comment by d4rkc0d3r** [comment]
3.9.0 is out and fixes this issue
