### ISSUE TITLE
Shader errors with latest version of Silent's Crosstone

### ISSUE THREAD

**Issue by rskskr** [d4rkc0d3r/d4rkAvatarOptimizer#18]
The latest release of Silent's Crosstone (still on the testing branch for now) is yielding errors that visually look similar to issue https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/issues/5 with stair-stepped shadows. This is when running the optimizer with the same settings as before, with only merging different materials checked, along with same dimension textures.

![Unity_nDQhpnYq6a](https://user-images.githubusercontent.com/52654735/204144643-872d1ffa-9077-4aee-8023-e7d0303ff6f4.png)

The Unity console shares these errors with me:

![Unity_zNxVq4V1CI](https://user-images.githubusercontent.com/52654735/204144700-cdbc9ba1-4e8d-443d-9e41-11023ff81f62.png)

And the offending generated shaders: 

[shaders.zip](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/files/10098679/shaders.zip)

**Comment by rskskr** [comment]
This has since been fixed (unintentionally) in an update of the shader!

**Comment by d4rkc0d3r** [comment]
[It wasn't unintentionally!](https://gitlab.com/s-ilent/SCSS/-/commit/2c32aaba97ff6ec6395aac3d98476d27f8ec9a2b)

Anyways I'll reopen this since I haven't fixed it on my end. The issue comes from applying all keywords to all passes even if the pass doesn't have the corresponding shader feature pragmas.
