### ISSUE TITLE
MissingReferenceException: The object of type 'SkinnedMeshRenderer' has been destroyed

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#45]
I have tried the optimizer with modular avatar. Sometime I succeed, some time not. Here is the console information.

![Screenshot_5](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/e32abc63-1446-4d5b-8032-251692fd5245)

MissingReferenceException: The object of type 'SkinnedMeshRenderer' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
d4rkAvatarOptimizer.GetPathToRoot (UnityEngine.Component component) (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:585)
d4rkAvatarOptimizer.FindAllPhysBonesToDisable () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:1699)
d4rkAvatarOptimizer.Optimize () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:139)
d4rkAvatarOptimizerEditor.OnInspectorGUI () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizerEditor.cs:130)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by d4rkc0d3r** [comment]
Thanks for the report. While I investigate this you can try to uncheck "Disable Phys Bones When Unused" if the error keeps happening to you.

**Comment by jerryzmtz** [comment]
> 

Thanks! By the way, could you elaborate more on option "merge cull back with cull off"? I have read the documentations and still not know whether I should click the option or not. I know the best way is to use cull back for all shader, but let's say there is a 20,000 polygons dress(cull off) and 70,000 polygons others (cull back), should I click this option or not?

**Comment by d4rkc0d3r** [comment]
If you click that option it allows the optimizer to potentially change cull back to cull off on a material if it helps merging the material with others (this is a very rare occurrence, it saves 0-1 materials on my own models). If the preview material count doesn't change this option does nothing.  
As you said there is no obviously better way here. Culling off is slightly higher gpu load but having more materials is higher cpu load. IMO the higher gpu cost is not very significant compared to the cpu overhead since in larger instances you'll be mostly cpu bound. The reason the option is disabled by default is because a shader might rely on cull back to show up correctly.

My recommendation is to just have it on an see if everything still looks all right, if not disable it.

**Comment by d4rkc0d3r** [comment]
I could reproduce this by setting a mesh to EditorOnly which is affected by a PhysBone that has no other dependencies besides said mesh.  
The problem was caused by invalid cached data from before EditorOnly objects got deleted.
