### ISSUE TITLE
Material merging results in corrupted material/textures

### ISSUE THREAD

**Issue by rskskr** [d4rkc0d3r/d4rkAvatarOptimizer#5]
Using Silent's Crosstone, I've been trying to merge 4 materials together, but the results are a bit... complicated.

There's something like a 50-50 chance that the merged materials result as either 

![Unity_vhzFT5Lbz9](https://user-images.githubusercontent.com/52654735/185630916-ad25be4d-5072-4e31-bfb9-173aba5d0647.png)

or 

![Unity_dUrDqaVgFh](https://user-images.githubusercontent.com/52654735/185630951-091c6964-7273-4223-8fb5-2de16e207323.png)

The latter looks almost right, but with strange shadow stepping along the hair.

Both produce an identical error message: 

![Unity_3Enc5MqoGa](https://user-images.githubusercontent.com/52654735/185631427-651bd096-2ea9-42f0-8435-f1e00e1f1894.png)

I've attached the resulting shader/material for result 1 and 2. 
[result 1.zip](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/files/9382645/result.1.zip)
[result 2.zip](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/files/9382644/result.2.zip)

**Comment by d4rkc0d3r** [comment]
The first result looks like you used crunch compression on your textures. Texture arrays don't support crunch compression, I will add a warning for that.

**Comment by rskskr** [comment]
Oops, you're right, I was using crunch compression. With it disabled, I can consistently get the 2nd result now. Same error.

**Comment by d4rkc0d3r** [comment]
I added a warning for crunch compressed textures as well as stop it from trying to merge them.
I also inline replace the `UNITY_POSITION` macro since it seems to always resolve to the same thing anyways. You can download the [newest code](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip) to get the fix.

**Comment by Vladislav-G** [comment]
Thank you, again! That solved the issue, but I inadvertently found something else I think. I noticed that if I merge materials where one of them has a normal map and the others do not, I can run into broken normals after optimising. Is this by design, and should I instead include a flat (128, 128, 255 rgb) normal map for the rest? Below is a before/after optimising.

![Unity_LEnsF4ze1r](https://user-images.githubusercontent.com/5969035/185656468-c7234de6-9f39-4766-b9c0-1012449d42d5.png)
![Unity_fUrMVd7Vc3](https://user-images.githubusercontent.com/5969035/185656480-134d2d60-19e6-4ad9-864a-093d5484df60.png)

**Comment by rskskr** [comment]
Thank you, again! That solved the issue, but I inadvertently found something else I think. I noticed that if I merge materials where one of them has a normal map and the others do not, I can run into broken normals after optimising. Is this by design, and should I instead include a flat (128, 128, 255 rgb) normal map for the rest? Below is a before/after optimising.

![Unity_LEnsF4ze1r](https://user-images.githubusercontent.com/52654735/185657698-626d14bb-34e3-4f2f-b090-762cb6ebc25b.png)
![Unity_fUrMVd7Vc3](https://user-images.githubusercontent.com/52654735/185657701-1ed67853-35a0-4261-8c89-a918aabe25bf.png)

**Comment by d4rkc0d3r** [comment]
Looks like the unity docs page lied about the default bump texture value. I figured it out and fixed it, thanks for the report.
