### ISSUE TITLE
Optimize Fails if GameObject 'Body' is present

### ISSUE THREAD

**Issue by teehzero** [d4rkc0d3r/d4rkAvatarOptimizer#54]
https://i.imgur.com/vlmImL4.png
https://i.imgur.com/nwJ0Frh.png

Had to rename my face mesh. This used to not be a problem? v3.1.2

**Comment by d4rkc0d3r** [comment]
You have a different GameObject called Body that is a sibling to your face mesh (riiiight at the bottom of your screenshot). Having sibling GameObjects with the same name in unity is in general a bad idea. My optimizer uses paths of transforms relatively often and having a path resolve to different GameObjects is not good. I don't even know how animators handle that since they also go by paths...

If the UI is spamming errors then I'd like to fix that and also want to add a warning if there exists same named siblings. Can you show me the full error message that shows when you click on it?

**Comment by teehzero** [comment]
You were right! Renaming that second GO named "Body" allows the optimizer to do its thing.
