### ISSUE TITLE
Unexpected optimization with regard to "Pickup PB Gimmick"

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#61]
Don't know whether it is possible to be detected automatically, but it seems that a PB setup like this (Screenshot 1) will break unexpectedly, when you enable "Delete Unused Components" or "Delete Unused GameObjects"

Delete Unused Components (Screenshot 2): Will delete the PB which is useful for pickup.
Delete Unused GameObjects (Screenshot 3): Will delete intermediate object which is referred by the PB. In this case, it is "GlassesObj"

This setup is usually useful for "Pickup" related gimmicks, with which one could pickup a MeshRender to some extent. It needs to put a MeshRender under a bone. eg. Bone1/Bone2/MeshRender.

![Screenshot1](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/ecf5760c-c4f5-44af-8b95-d470866204e0)
![image_2023-11-02_19-07-14](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/5afcbc43-fc21-4d85-af26-1cfea7ff0475)
![image_2023-11-02_19-08-06](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/6efd411c-d148-41e0-b27a-f17f6ec8a05c)

**Comment by d4rkc0d3r** [comment]
> Delete Unused Components (Screenshot 2): Will delete the PB which is useful for pickup.

This is a pretty straight forward bug on my side. The dependency check only added game objects on moving transforms of the PB and since the glasses obj is in the ignore list it doesn't see it. This is ofc just wrong logic on my implementation, it should add all child components as dependencies.

> Delete Unused GameObjects (Screenshot 3): Will delete intermediate object which is referred by the PB. In this case, it is "GlassesObj"

Yup I forgot to add the PB ignore transforms to the list of used game objects. In that screenshot I also see it deleting Bone02 which I can't actually explain, unlike the GlassesObj which shouldn't get deleted since its referenced. Bone02 should still be in the list of game objects moved by the phys bone so dunno why it disappears.

Thanks for the detailed bug report!

**Comment by d4rkc0d3r** [comment]
should be fixed with 3.2.2
