### ISSUE TITLE
Optimise fails on unity 2022 due to non humanoid avatar

### ISSUE THREAD

**Issue by arianwen27** [d4rkc0d3r/d4rkAvatarOptimizer#67]
Updated most of my avatars to 2022 and friends have done the same. All our avatars fail to build/optimise with dr4k with an error saying the avatar type is not humanoid. The avatar is in fact humanoid. 1 of my avatars works for unknown reasons. Saw a similar issue report saying build fails when avatar type is read as null, though I believe that was fixed. The non humanoid error still persists, fix is to disable d4rk till it's updated with a fix.

Would like to give more details but all I really have is "it worked before unity 2022 and the error says the avatar is not humanoid"

**Comment by d4rkc0d3r** [comment]
>  Saw a similar issue report saying build fails when avatar type is read as null, though I believe that was fixed.

It's the same bug and only fixed on my dev version.

The avatar the error complains about is a unity avatar component which is part of every animator on your vrc avatar. Since you said your avatar is in fact humanoid, that means you have some extra Animator components somewhere which are not humanoid.

**Comment by arianwen27** [comment]
Ah, thought it was fixed in a general release. Thanks for the quick reply, apologies for the unneeded issue report as you've already handled this, just not publicly yet.
