### ISSUE TITLE
Poi Shader error 3.4.1

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#81]
Some materials cause error after optimizations. 

VRCSDK 3.5.1
Poiyomi 8.1.167
VRCFury 1.786.0

![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/93beec3a-766a-4628-894c-e14e55abbda2)
[TrashBin.zip](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/files/14428960/TrashBin.zip)

**Comment by jerryzmtz** [comment]
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/24bfc52d-c3ea-4532-9c87-4cc9dd435083)

**Comment by d4rkc0d3r** [comment]
You seem to have an animation that animates the material property `_GL_Level Min`. This however has a space in it which is invalid for material properties. What shader does that belong to?

**Comment by jerryzmtz** [comment]
> You seem to have an animation that animates the material property `_GL_Level Min`. This however has a space in it which is invalid for material properties. What shader does that belong to?

It should be a material propery of sunao shader, which should be a missing animation paths before optimizations

**Comment by d4rkc0d3r** [comment]
I looked at sunao shader and didn't see any property that looks remotely like it.  
Not like the property can exist on any shader at all since it contains a space. I really don't understand how you even ended up with an animation that animates something that can't possibly exist in the first place...
