### ISSUE TITLE
GOGO LOCO height breaking

### ISSUE THREAD

**Issue by aspwil** [d4rkc0d3r/d4rkAvatarOptimizer#98]
when the optimizer is run on a model with gogoloco in it it appears to break the height function of gogoloco, with only the feet moving. i am using optimizer version 3.6.1 and the vrcfury prefrab for gogo 1.8.3 with vrcfury version 1.859.0

i have confirmed that this issues does not occur when the optimizer is not used, but when it is it breaks the height function

even with only optimize on upload ticked it still breaks.

**Comment by Toys0125** [comment]
I can confirm that that happens to me as well.

**Comment by AsaNekoo** [comment]
I can confirm as well. on Unity 2022.3.22f1.

**Comment by d4rkc0d3r** [comment]
I can't reproduce this issue. Where exactly does it break for you?
 * In game
 * In editor with gesture manager
 * In editor with av3 emulator

I am myself not familiar with gogo loco but I tested it on an avatar with av3 emulator in editor real quick and toggling any of the sitting/lying down animations and then using the ufo slider does move the entire avatar up and down.

**Comment by AsaNekoo** [comment]
In game

**Comment by Toys0125** [comment]
Sadly, it seems that the Unity editor doesn't showcase the issue. All I know is that having the optimizer active causes ggLoco to break in-game. Desktop or while in VR.

**Comment by aspwil** [comment]
my testing was done on an avi with all toggles etc stripped out, only a base mesh + avi descripter, with gogoloco via vrcfury prefab, and using the optimizer with only "optimize on upload" ticked (no other options) 

re-looking into it, i may have accidentally left the ASL controllers on, but i dont think thats the cause.

either "optimize on upload" has some extra functions that cant be turned off, or the very script itself is doing something that is messing with gogo locos functions.

this is an issue categorized [here](https://teeth-fetch-gdl.craft.me/CxY701Ne9Ng5Ev/b/64C5CE60-8C73-4E27-981C-99E30DEAF29C/Viewpoint-not-moving-) in the gogo loco docs, and claims its often an issues caused by things messing with the action layers

in personal talks with the creator of GOGOLOCO (you can join the discord to get in contact with them if need be) they said 

"Probably because they remove the go empty animation
Since the path is broken on purpose"

which is just speculation on a possible issue as far as i know. (i don't think they looked into the actual code of this optimizer)

it also seems to have some relation to the switch to the newer version of the unity editor (2022.3.22f1 instead of 2022.3.6f1) though i have not tested to confirm if this issue is unique to 2022.3.22f1

**Comment by d4rkc0d3r** [comment]
> either "optimize on upload" has some extra functions that cant be turned off

it does do several things always. see the [readme](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer?tab=readme-ov-file#create-optimized-copy) for a list.

> "Probably because they remove the go empty animation Since the path is broken on purpose"

I specifically handle cases where all curves in an animation get deleted because they don't reference anything by injecting a new broken binding with a length that should match the longest deleted curve.

Either that part broke somehow or the unity version bump changed something about asset serialization that makes something not save correctly. The second would explain it working in editor but not in game.

**Comment by Toys0125** [comment]
> Either that part broke somehow or the unity version bump changed something about asset serialization that makes something not save correctly. The second would explain it working in editor but not in game.

I actually want to talk about that since I know that your script had an issue with the Dex clone system that would error out the serialization a while back, and they had to hack their code to fix the issue.
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/15334903/cef488d4-b64d-43d2-a9b3-4b7b51d16363)

**Comment by d4rkc0d3r** [comment]
It wasn't the serialization and instead the first thing. The broken curve I generate doesn't work in 2022.3.22f1 because I used `EditorCurveBinding.DiscreteCurve` instead of `EditorCurveBinding.FloatCurve`

Switching to the latter does solve this issue and also #99
